name: Setup Linux

description: Set up Docker workspace on EC2

inputs:
  BRANCH:
    required: true
    description: 'The branch, tag, or SHA to checkout'


runs:
  using: composite
  steps:
    - name: Zain Composite act
      shell: bash
      run: echo "look ma, i'm composed!"
    - name: Get input branch ref name
      shell: bash
      run: echo "Branch ref name is ${{ inputs.BRANCH || github.event_name == 'pull_request' || github.sha }}"
    - name: Zain Composite act 2
      if: github.repository_owner == 'pytorch'
      shell: bash
      run: echo "look ma, i'm composed 2!"
    - name: Zain Composite act 3
      if: github.repository_owner != 'pytorch'
      shell: bash
      run: echo "look ma, i'm composed 3!"
    - name: Zain Composite act 4
      shell: bash
      run: echo "look ma, i'm composed 4!"
