name: Setup Linux

description: Zain's compostie action

inputs:
  pytorch-repo-directory:
    description: Path to root of pytorch repo
    default: .

runs:
  using: composite
  steps:
    - shell: bash
      run: |
          set -ex
          ls -l
          pushd ${{ inputs.pytorch-repo-directory }} && ls -l
          ls -l
          popd
          ls -l
