name: linux-binary-build

on:
  workflow_call:
    inputs:
      package_type
      desired_cuda
      gpu_arch_version
      gpu_arch_type
      container_image
      package_type
      libtorch_config
      libtorch_variant

jobs:
  build:
    # Don't run on forked repos.
    if: github.repository_owner == 'pytorch'
    runs-on: linux.4xlarge
    timeout-minutes: 240
    env:
      PACKAGE_TYPE: !{{ config["package_type"] }}
      # TODO: This is a legacy variable that we eventually want to get rid of in
      #       favor of GPU_ARCH_VERSION
      DESIRED_CUDA: !{{ config["desired_cuda"] }}
      GPU_ARCH_VERSION: !{{ config["gpu_arch_version"] }}
      GPU_ARCH_TYPE: !{{ config["gpu_arch_type"] }}
      DOCKER_IMAGE: !{{ config["container_image"] }}
      SKIP_ALL_TESTS: 1
{%- if config["package_type"] == "libtorch" %}
  {%- if config["libtorch_config"] %}
      LIBTORCH_CONFIG: !{{ config["libtorch_config"] }}
  {%- endif %}
      LIBTORCH_VARIANT: !{{ config["libtorch_variant"] }}
  {%- if config["devtoolset"] %}
      DESIRED_DEVTOOLSET: !{{ config["devtoolset"] }}
  {%- endif %}
  {%- if is_windows %}
      # This is a dummy value for libtorch to work correctly with our batch scripts
      # without this value pip does not get installed for some reason
      DESIRED_PYTHON: "3.7"
  {%- endif %}
  {%- else %}
      DESIRED_PYTHON: "!{{ config["python_version"] }}"
{%- endif %}
