name: buck

on:
  push:
    tags:
      # Trigger on release candidate builds
      # Release candidate tags look like: v1.11.0-rc1
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
      - 'ciflow/trunk/*'
    branches:
      - master
      - main
      - release/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -e -l {0}

jobs:

  buck-build-test:
    runs-on: ubuntu-latest
    env:
      JOB_BASE_NAME: ubuntu-latest-buck
    steps:
      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@master

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          activate-environment: build

      - name: Install dependencies
        run: |
          conda install -y \
            cffi \
            cmake \
            mkl \
            mkl-include \
            ninja \
            numpy \
            pyyaml \
            requests \
            setuptools \
            typing_extensions

      - name: Install Buck
        run: |
          wget https://github.com/facebook/buck/releases/download/v2021.01.12.01/buck.2021.01.12.01_all.deb
          sudo apt install ./buck.2021.01.12.01_all.deb

      - name: Code Generation
        run: |
          cd third_party
          python generate-xnnpack-wrappers.py
          cd ..

      - name: Build Buck target
        run: |
          echo -e "" > .buckconfig
          buck build --config-file oss.buckconfig c10:c10 third_party: aten/src/ATen/native/quantized/cpu/qnnpack: --keep-going
