name: docker-builds

on:
  workflow_dispatch:
  pull_request:
    paths:
      - Dockerfile
      - docker.Makefile
  push:
    branches:
      - master
      - main
      - release/*
      - landchecks/*
    paths:
      - Dockerfile
      - docker.Makefile
  schedule:
    - cron: 1 3 * * 3

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

env:
  BUILD_TYPE: official
  BUILD_PROGRESS: plain
  # WITH_PUSH: ${{ github.event_name == 'schedule' }}

jobs:
  build:
    runs-on: [self-hosted, linux.2xlarge]
    timeout-minutes: 240
    strategy:
      matrix:
        image_type: [devel, runtime]
        platform: [linux/arm64, linux/amd64]
      exclude:
        # nvidia specific images don't exist for arm64 so only build the runtime image
        - image_type: devel
          platform: linux/arm64
    env:
      BUILD_PLATFORMS: ${{ matrix.platform }}
      DOCKER_ORG: pytorch
      BUILD: buildx
    steps:
      # [see note: pytorch repo ref]
      # deep clone (fetch-depth 0) required for git merge-base
      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@master
      - name: Setup Linux
        uses: ./.github/actions/setup-linux
      # Setup multi-arch image builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        env:
          QEMU_BINARY_PATH: ${{ runner.temp }}/bin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Setup job specific variables
        run: |
          echo "${RUNNER_TEMP}/bin" >> "${GITHUB_PATH}"
      - name: Setup linux/arm64 specific variables
        if: ${{ matrix.platform == "linux/arm64" }}
        run: |
          echo "CUDA_VERSION=cpu" >> "${GITHUB_ENV}"
