name: pull

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - release/*
      - landchecks/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  linux-focal-py3_7-gcc7-build:
    name: linux-focal-py3.7-gcc7
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-focal-py3.7-gcc7
      docker-image-name: pytorch-linux-focal-py3.7-gcc7

  macos-12-py3-x86-64-build:
    name: macos-12-py3-x86-64
    uses: ./.github/workflows/_mac-build.yml
    with:
      build-environment: macos-12-py3-x86-64
      xcode-version: "13.3.1"
      runner-type: macos-12-xl
      build-generates-artifacts: true
    secrets:
      MACOS_SCCACHE_S3_ACCESS_KEY_ID: ${{ secrets.MACOS_SCCACHE_S3_ACCESS_KEY_ID }}
      MACOS_SCCACHE_S3_SECRET_ACCESS_KEY: ${{ secrets.MACOS_SCCACHE_S3_SECRET_ACCESS_KEY }}

  macos-12-py3-x86-64-test:
    name: macos-12-py3-x86-64
    uses: ./.github/workflows/_mac-test.yml
    needs: macos-12-py3-x86-64-build
    with:
      build-environment: macos-12-py3-x86-64
      test-matrix: |
        { include: [
          { config: "functorch", shard: 1, num_shards: 1, runner: "macos-12" },
        ]}
    secrets:
      AWS_OSSCI_METRICS_V2_ACCESS_KEY_ID: ${{ secrets.AWS_OSSCI_METRICS_V2_ACCESS_KEY_ID }}
      AWS_OSSCI_METRICS_V2_SECRET_ACCESS_KEY: ${{ secrets.AWS_OSSCI_METRICS_V2_SECRET_ACCESS_KEY }}
