name: pull

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - release/*
      - landchecks/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  win-vs2019-cpu-py3-build:
    name: win-vs2019-cpu-py3
    uses: ./.github/workflows/_win-build.yml
    with:
      build-environment: win-vs2019-cpu-py3
      cuda-version: cpu

  win-vs2019-cpu-py3-test:
    name: win-vs2019-cpu-py3
    uses: ./.github/workflows/_win-test.yml
    needs: win-vs2019-cpu-py3-build
    with:
      build-environment: win-vs2019-cpu-py3
      cuda-version: cpu
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 2, runner: "windows.4xlarge" },
          { config: "default", shard: 2, num_shards: 2, runner: "windows.4xlarge" },
          { config: "functorch", shard: 1, num_shards: 1, runner: "windows.4xlarge" },
        ]}
