name: pull

on:
  push:
    branches:
      - zainr/*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  job-one:
    name: job one
    uses: ./.github/workflows/_zain-reusable.yml
    with:
      action-name: ./.github/actions/zainr-action
  job-two:
    name: job two
    uses: ./.github/workflows/_zain-reusable.yml
    with:
      action-name: ./.github/actions/zainr-action-the-second

  # the-first-job:
  #   runs-on: linux.20_04.16x
  #   name: Zain's First Job
  #   steps:
  #     - name: First step
  #       run: echo "hi there"
  #     - name: Let's checkout some actions
  #       uses: actions/checkout@v3
  #     - name: action time - no dir
  #       uses: ./.github/actions/zainr-action
  #     - name: action time - android dir
  #       uses: ./.github/actions/zainr-action
  #       with:
  #         pytorch-repo-directory: android
  #     - name: action time - test dir
  #       uses: ./.github/actions/zainr-action
  #       with:
  #         pytorch-repo-directory: test
